<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Hamdy" ignored="0" name="Test" tests="2" failures="1" timestamp="23 Feb 2018 13:04:18 GMT" time="0.088" errors="0">
  <testcase name="fail" time="0.032" classname="Test11.Test11">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]at Test11.Test11.fail(Test11.java:22)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- fail -->
  <testcase name="pass" time="0.0" classname="Test11.Test11"/>
</testsuite> <!-- Test -->
